#27 팔로우, 팔로잉모달UI / 프로필필api연결
Leets-Official/Z-FE pull request #30
Opened 2024-11-12 08:54 UTC by JJJiL0ng

## 📝 개요

프포필에서 팔로워 팔로잉을 보는 모달 ui를 추가하고 프로필에 필요한 api들을 연결중입니다
## ✨ 변경 사항

- 코드나 기능의 주요 변경 사항을 설명합니다.

  - ✨ 내프로필 상대프로필 ui를 수정하였습니다(배경사진 없앰, 채팅 버튼 추가)
  -  ✨ 모달 ui - 팔로워 팔로잉을 볼 수 있는 모달입니다
  - ✨ 프로필 api연결: 팔로워 리스트, 팔로잉 리스트, 작성한 게시물 보기 api연결

## 🔗 관련 이슈
closes #27 

## 📸 스크린샷 (옵션)
<img width="602" alt="image" src="https://github.com/user-attachments/assets/581a4e5a-8769-4ebb-b405-21cfe9de0339">
<img width="600" alt="image" src="https://github.com/user-attachments/assets/0ec16423-8201-4512-9584-fd013161d984">
<img width="609" alt="image" src="https://github.com/user-attachments/assets/9e65a98c-a3f3-4650-b4f6-de6a1bd43d50">
<img width="604" alt="image" src="https://github.com/user-attachments/assets/a1fa47fa-030e-4294-97f0-721bd187cd9f">

- UI 변경 사항이 있는 경우 스크린샷을 포함합니다.

## ℹ️ 참고 사항

현재 json에러가 나는데 이게 연결이 안돼서 그런건지 잘 모르겠습니다

2024-11-12 09:24 UTC, Minkyu0424 reviewed
코멘트 사항 중에 헷갈리거나 모르는거 있으시면 바로바로 물어봐주시구, 진행상황 추적을 위해 작업 내용 꾸준히 머지해주세요

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/api/followApis/follower/route.ts
> +    const response = await fetch(`/api/follows/followers?tag=${tag}`);
현재 api 폴더가 followApis로 시작하는데 그거에 맞게 /followApis/api/follows/followers?tag=${tag} 로 요청하는게 맞아보입니다.

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/api/followApis/following/route.ts
> +  }
이런 interface들은 재활용 및 가독성을 위해 _types폴더에 따로 선언해주세요

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/api/followApis/following/route.ts
> +    const response = await fetch(`/api/follows/followings?tag=${tag}`);
해당 경로도 위에서 말한 것과 동일하게 수정해주시면 될 것 같습니다.

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/components/profile/FollowerListModal.tsx
여러 요소가 한 곳에 있다보니 코드가 길어 진 것 같습니다. 타입, 상수들은 해당 목적에 맞는 폴더에 선언해주시면 코드가 이뻐질 것 같아요

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/components/profile/FollowerListModal.tsx
> +  // 팔로우/언팔로우 토글 (임시 구현)
팔로우 언팔로우 api는 연결 아직 안한거죠?

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/components/profile/FollowerListModal.tsx
> +        {isLoading && (
로딩, 에러에 대한 ui는 일단 구현을 마치고 향후 기능 개선에서 해도 좋을 거 같아요..

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/components/profile/FollowingListModal.tsx
> +                  <button
지금은 시간이 부족해서 될지 모르겠지만 아마 사용하시는 버튼이 배경색만 다르고 나머지 버튼 스타일링은 같을 거라 제가 Button Component 사용하신거 보면 좀 더 재사용면이나 가독성면에서 좋을거에요

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/components/profile/OtherProfile.tsx
> +    <path d="M16.95 7.76661L5.28336 1.93328C4.82293 1.70412 4.30304 1.62254 3.79455 1.69965C3.28607 1.77677 2.81374 2.00884 2.44197 2.36421C2.07019 2.71958 1.81707 3.18096 1.7171 3.68545C1.61713 4.18
제가 만든 Icon 컴포넌트 사용하시면 코드 훨씬 줄 것 같아요!
IconPath.ts에 가져오실 svg에 대한 내용을 선언하고 해당한 아이콘 name명을 Icons.tsx 컴포넌트를 가져오면서 name props에 넣어주면 됩니다. 제 코드 참고해주세요!

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/api/followApis/follower/route.ts
> +    const response = await fetch(`/api/follows/followers?tag=${tag}`);
제가 잘못봤네요 각 컴포넌트에서 요청하는 경로를 해당 코멘트에 맞게 경로 수정하고 
해당 컴포넌트에서 요청하는 경로는 실제 백엔드 서버로 요청해야하기에 환경변수에서 서버 URL에 해당하는 값을 앞에 붙여서 요청 보내야합니다.

`const SERVER_URL = process.env.NEXT_PUBLIC_SERVER;
SERVER_URL/api/follows/followers?tag=${tag}`

2024-11-12 09:24 UTC, Minkyu0424 commented on src/app/components/profile/OtherProfile.tsx
>            <Link href="/" className="rounded-full hover:bg-gray-200 p-2">
뒤로가기 버튼이라 상대 프로필을 클릭할 상황을 생각하면 게시물 상세에서 이동하는 경우도 있기에 / 경로가 아닌 뒤로가기 함수를 쓰는게 좋을 것 같아요
```

const router = useRouter();

  const handleGoBack = () => {
    router.back();
  };
  
```

2024-11-12 17:16 UTC, One-HyeWon requested changes

2024-11-12 17:16 UTC, One-HyeWon commented on src/app/api/followApis/following/route.ts
> +const SERVER_URL = process.env.NEXT_PUBLIC_SERVER || "http://43.203.123.147:8080";
오른쪽의 로컬 주소도 환경 변수로 빼주세요!

2024-11-12 17:16 UTC, One-HyeWon commented on src/app/components/profile/FollowerListModal.tsx
> +                 </button>
공통 버튼 컴포넌트가 따로 있지 않으신가요? 있으시다면, 해당 컴포넌트를 사용하면 좋을 것 같습니다!

2024-11-12 17:16 UTC, One-HyeWon commented on src/app/components/profile/FollowingListModal.tsx
> +        )}
에러, 로딩에 대한 페이지/컴포넌트는 추후 작업이 필요해보입니다
따라서 api 상태에 따른 라우팅이 필요할 것 같습니다

2024-11-13 02:56 UTC, JJJiL0ng commented on src/app/api/followApis/following/route.ts
> +const SERVER_URL = process.env.NEXT_PUBLIC_SERVER || "http://43.203.123.147:8080";
넵 수정했습니다!

2024-11-13 11:39 UTC, One-HyeWon approved these changes

2024-11-13 14:07 UTC, merged